services:
  python-server:
    image: "w4t3rcs/spring-boot-python-executor-python-grpc-server"
    ports:
      - "50051:50051"
    environment:
      PYTHON_SERVER_USERNAME: root
      PYTHON_SERVER_PASSWORD: pass
      PYTHON_ADDITIONAL_IMPORTS: scikit-learn,numpy,pandas