# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'python.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpython.proto\x12\x06python\"\x1f\n\rPythonRequest\x12\x0e\n\x06script\x18\x01 \x01(\t\" \n\x0ePythonResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x96\x01\n\rPythonService\x12;\n\x08SendCode\x12\x15.python.PythonRequest\x1a\x16.python.PythonResponse\"\x00\x12H\n\x13StreamCodeExecution\x12\x15.python.PythonRequest\x1a\x16.python.PythonResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PYTHONREQUEST']._serialized_start=24
  _globals['_PYTHONREQUEST']._serialized_end=55
  _globals['_PYTHONRESPONSE']._serialized_start=57
  _globals['_PYTHONRESPONSE']._serialized_end=89
  _globals['_PYTHONSERVICE']._serialized_start=92
  _globals['_PYTHONSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
