# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import python_pb2 as python__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in python_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCode = channel.unary_unary(
                '/python.PythonService/SendCode',
                request_serializer=python__pb2.PythonRequest.SerializeToString,
                response_deserializer=python__pb2.PythonResponse.FromString,
                _registered_method=True)
        self.StreamCodeExecution = channel.unary_stream(
                '/python.PythonService/StreamCodeExecution',
                request_serializer=python__pb2.PythonRequest.SerializeToString,
                response_deserializer=python__pb2.PythonResponse.FromString,
                _registered_method=True)


class PythonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCodeExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCode,
                    request_deserializer=python__pb2.PythonRequest.FromString,
                    response_serializer=python__pb2.PythonResponse.SerializeToString,
            ),
            'StreamCodeExecution': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCodeExecution,
                    request_deserializer=python__pb2.PythonRequest.FromString,
                    response_serializer=python__pb2.PythonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'python.PythonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('python.PythonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/python.PythonService/SendCode',
            python__pb2.PythonRequest.SerializeToString,
            python__pb2.PythonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCodeExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/python.PythonService/StreamCodeExecution',
            python__pb2.PythonRequest.SerializeToString,
            python__pb2.PythonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
