spring:
  application:
    name: example
  python:
    executor:
      type: local
    resolver:
      declared: spelython, py4j, restricted_python, result
    py4j:
      enabled: true
      auth-token: token