spring:
  application:
    name: demo-app
  profiles:
    active: ml
  python:
    cache:
      enabled: true
    executor:
      type: rest
      rest:
        token: secret
  cache:
    type: caffeine
    cache-names: bobi, fileBodiesCache, filePathsCache, pythonResolverCache, pythonExecutorCache, pythonProcessorCache
  docker:
    compose:
      file: ./demo-app/docker-compose.yaml